config/routes.rb
Aconverter::Application.routes.draw do
  resources :user_files
  match '/users/files/:file_id/save' => 'user_files#send_to_save'
  match '/users/:user_id/files/get' => 'users#ajax_get'

  match '/friendships/new-friendship' => 'friendships#new_friendship'
  match '/friendships/destroy-friendship' => 'friendships#destroy_friendship'

  match '/users/search' => 'users#search'
  resources :friendships

  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :users
  root :to => 'users#index'

end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :user_id, :input_format, :output_format, :file_name, :content_type, :status
  before_save      UploadWrapper.new
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  before_filter :require_login

  # GET /user_files
  # GET /user_files.json
  def index
    @user_files = UserFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_files }
    end
  end

  # GET /user_files/1
  # GET /user_files/1.json
  def show
    @user_file = UserFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_file }
    end
  end

  # GET /user_files/new
  # GET /user_files/new.json
  def new
    @user_file = UserFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_file }
    end
  end

  # GET /user_files/1/edit
  def edit
    @user_file = UserFile.find(params[:id])
  end

  # POST /user_files
  # POST /user_files.json
  def create
    @user_file = UserFile.new
    respond_to do |format|
      if params.has_key?(:user_file)
        uploaded_io = params[:user_file][:name]
        if uploaded_io.present?
          upload_dir = Rails.root.join('public', 'uploads')
          Utils.check_folder(upload_dir)
          if Utils.check_content_type(uploaded_io.content_type)
            File.open(upload_dir.join(Utils.conver_file_name(uploaded_io.original_filename)), 'wb') do |file|
              if file.write(uploaded_io.read)
                @user_file.name = Utils.conver_file_name(uploaded_io.original_filename)
                @user_file.user = current_user
                @user_file.content_type = uploaded_io.content_type
                @user_file.status = 'queued'
                if @user_file.save()
                  format.html { redirect_to current_user }
                  format.json { render json: @user_file, status: :created, location: users_path }
                else
                  format.html { render action: 'new' }
                  format.json { render json: @user_file.errors, status: :unprocessable_entity }
                end
              else
                format.html { render action: 'new' }
                format.json { render json: @user_file.errors, status: :unprocessable_entity }
              end
            end
          else
            flash[:notice] = 'File type is not supproted'
            format.html { render action: 'new' }
            format.json { render json: @user_file.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:notice] = 'Choose file before upload'
        format.html { render action: 'new' }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_files/1
  # PUT /user_files/1.json
  def update
    @user_file = UserFile.find(params[:id])

    respond_to do |format|
      if @user_file.update_attributes(params[:user_file])
        format.html { redirect_to @user_file, notice: 'User file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_files/1
  # DELETE /user_files/1.json
  def destroy
    @user_file = UserFile.find(params[:id])
    @user_file.destroy

    respond_to do |format|
      format.html { redirect_to user_files_url }
      format.json { head :no_content }
    end
  end

  def check_status
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: {:status => session[:status].present?} }
    end
  end


  def send_to_save
    if params[:file_id].present?
      file_obj = UserFile.find(params[:file_id])
      @user = file_obj.user
      file_path = Rails.root.join('public', 'uploads',  file_obj.file_name+file_obj.output_format)
      if File.file?(file_path)
        File.open(file_path, 'rb') do |file|
          send_file(file, :filename =>  file_obj.name+file_obj.output_format, :stream => true, :buffer_size => 4096)
        end
      else
        respond_to do |format|
          format.html { redirect_to @user }
        end
      end
    end

  end

  protected

  def require_login
    unless user_signed_in?
      #flash[:error] = "You must be logged in to access this section"
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/user_files/_form.html.haml
= link_to 'Back to files list', current_user, :method => :get, :class => 'btn btn-primary'
.upload-file
  = form_for @user_file do |f|
    - if @user_file.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user_file.errors.count, "error")} prohibited this user_file from being saved:"
        %ul
          - @user_file.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.file_field :name
    .actions
      = f.submit 'Upload File', :class => 'btn btn-success'

app/views/user_files/edit.html.haml
%h1 Editing user_file

= render 'form'

= link_to 'Show', @user_file
\|
= link_to 'Back', user_files_path

app/views/user_files/index.html.haml
%h1 Listing user_files

%table
  %tr
    %th User
    %th Name
    %th
    %th
    %th

  - @user_files.each do |user_file|
    %tr
      %td= user_file.user_id
      %td= user_file.name
      %td= link_to 'Show', user_file
      %td= link_to 'Edit', edit_user_file_path(user_file)
      %td= link_to 'Destroy', user_file, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User file', new_user_file_path

app/views/user_files/new.html.haml
%h1 Upload New File

= render 'form'

app/views/user_files/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_file.user_id
%p
  %b Name:
  = @user_file.name

= link_to 'Edit', edit_user_file_path(@user_file)
\|
= link_to 'Back', user_files_path