config/routes.rb
Aconverter::Application.routes.draw do
  resources :user_files
  match '/users/files/:file_id/save' => 'user_files#send_to_save'
  match '/users/:user_id/files/get' => 'users#ajax_get'

  match '/friendships/new-friendship' => 'friendships#new_friendship'
  match '/friendships/destroy-friendship' => 'friendships#destroy_friendship'

  match '/users/search' => 'users#search'
  resources :friendships

  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :users
  root :to => 'users#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id, :is_active
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :require_login

  def new_friendship
    @friendship = Friendship.where(:user_id => params[:friend_id], :friend_id => current_user.id).first
    if @friendship.present?
      flash[:notice] = 'Added friend. Now you are friends'
      @friendship.is_active = true
    else
      flash[:notice] = 'Added friend. Wait for confirmation'
      @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    end
    if @friendship.save
      redirect_to root_url
    else
      flash[:error] = 'Unable to add friend.'
      redirect_to root_url
    end

  end

  def destroy_friendship

    @friendship = current_user.friendships.find_by_friend_id(User.find(params[:friend_id]))
    if @friendship.present?
      @friendship.destroy
      flash[:notice] = 'Removed friendship.'
    else
      @inverse_friendship = current_user.inverse_friendships.find_by_user_id(User.find(params[:friend_id]))
      if @inverse_friendship.present?
        @inverse_friendship.destroy
        flash[:notice] = 'Removed friendship.'
      end
    end

    redirect_to users_path
  end

  protected

  def require_login
    unless user_signed_in?
      #flash[:error] = "You must be logged in to access this section"
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.haml
= form_for @friendship do |f|
  - if @friendship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friendship.errors.count, "error")} prohibited this friendship from being saved:"
      %ul
        - @friendship.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :friend_id
    = f.number_field :friend_id
  .field
    = f.label :create
    = f.text_field :create
  .field
    = f.label :destroy
    = f.text_field :destroy
  .actions
    = f.submit 'Save'

app/views/friendships/edit.html.haml
%h1 Editing friendship

= render 'form'

= link_to 'Show', @friendship
\|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
%h1 Listing friendships

%table
  %tr
    %th User
    %th Friend
    %th Create
    %th Destroy
    %th
    %th
    %th

  - @friendships.each do |friendship|
    %tr
      %td= friendship.user_id
      %td= friendship.friend_id
      %td= friendship.create
      %td= friendship.destroy
      %td= link_to 'Show', friendship
      %td= link_to 'Edit', edit_friendship_path(friendship)
      %td= link_to 'Destroy', friendship, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Friendship', new_friendship_path

app/views/friendships/new.html.haml
%h1 New friendship

= render 'form'

= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%p#notice= notice

%p
  %b User:
  = @friendship.user_id
%p
  %b Friend:
  = @friendship.friend_id
%p
  %b Create:
  = @friendship.create
%p
  %b Destroy:
  = @friendship.destroy

= link_to 'Edit', edit_friendship_path(@friendship)
\|
= link_to 'Back', friendships_path