config/routes.rb
Aconverter::Application.routes.draw do
  resources :user_files
  match '/users/files/:file_id/save' => 'user_files#send_to_save'
  match '/users/:user_id/files/get' => 'users#ajax_get'

  match '/friendships/new-friendship' => 'friendships#new_friendship'
  match '/friendships/destroy-friendship' => 'friendships#destroy_friendship'

  match '/users/search' => 'users#search'
  resources :friendships

  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :users
  root :to => 'users#index'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Aconverter"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'Aconverter', users_path, {:class => 'brand'}
          .container.nav-collapse
            %p.navbar-text.pull-right
              - if user_signed_in?
                Logged in as
                %strong= current_user.email
                = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
                = link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'
              - else
                = link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'
                = link_to 'Login', new_user_session_path, :class => 'navbar-link'
                |
                = link_to 'Facebook', user_omniauth_authorize_path(:facebook), :class => 'navbar-link'
                = link_to 'Vkontakte', user_omniauth_authorize_path(:vkontakte), :class => 'navbar-link'
                = link_to 'Twitter', user_omniauth_authorize_path(:twitter), :class => 'navbar-link'
    .container.main-wrapper

      .row
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"